# Dependabot configuration for automatic dependency updates
# Minor and patch updates will be auto-merged by the dependabot-auto-merge.yml workflow
# Major updates require manual review

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    # Group patch updates together to reduce PR noise
    groups:
      patch-updates:
        update-types:
          - "patch"
    # Allow up to 10 open PRs at a time
    open-pull-requests-limit: 10
    # Add labels for easier filtering
    labels:
      - "dependencies"
      - "python"
    # Prefix commit messages
    commit-message:
      prefix: "deps"
      include: "scope"
